language: python
python:
  - "3.4"
before_install:
    - pip install pytest-cov
    - pip install coveralls  
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: py.test --cov=bucket_app tests/
after_success:
  - coveralls